### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by vt8235** [Ben-Kaniobi/Wim#11]
Tried to run it but got this:
![image](https://user-images.githubusercontent.com/3468816/30695655-2d19878a-9ed9-11e7-9cf9-3f620c1300d5.png)

**Comment by Ben-Kaniobi** [comment]
What version of AutoHotkey are you using? The problem seems to be the function `StrSplit(...)` which was added in v1.1.13

**Comment by vt8235** [comment]
thanks. it was 1.1.11. upgraded to 1.1.23 and it is now working.
